# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/docker/poky/meta \
  /home/docker/poky/meta-poky \
  /home/docker/poky/meta-yocto-bsp \
  /home/docker/meta-openembedded/meta-oe \
  /home/docker/meta-openembedded/meta-python \
  /home/docker/meta-openembedded/meta-networking \
  /home/docker/meta-openembedded/meta-webserver \
  /home/docker/meta-cfecfs \
  "
