# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

LAYERSERIES_COMPAT_cfecfs = "kirkstone scarthgap walnascar"

# We have recipe directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes/*/*.bb \
            ${LAYERDIR}/recipes/*/*.bbappend \ 
            ${LAYERDIR}/images/*.bb \
            ${LAYERDIR}/images/*.bbappend "

BBFILE_COLLECTIONS += "cfecfs"
BBFILE_PATTERN_cfecfs = "^${LAYERDIR}/"
BBFILE_PRIORITY_cfecfs = "7"
LAYERVERSION_cfecfs = "1"

