name: Docker Build & Push Action

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TGT_REPO: ghcr.io/${{ github.repository_owner }}

jobs:
  build-sdk:
    name: Build SDK Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-image: [ arm-linux-sdk, gaisler-sparc-rcc-sdk, rtems5-tools, rtems6-tools ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build and push image
        uses: ./.github/actions/build-image
        with:
          target-image: ${{ matrix.target-image }}
          registry-token: ${{ secrets.GITHUB_TOKEN }}

  build-basic:
    name: Build System/OS Images
    needs: build-sdk
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-image: [ cfsexec-qemu, cfsexec-linux, cfsexec-ubuntu22, rtems5-rtos, rtems6-rtos ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build and push image
        uses: ./.github/actions/build-image
        with:
          target-image: ${{ matrix.target-image }}
          registry-token: ${{ secrets.GITHUB_TOKEN }}

  build-buildenv:
    name: CFS Build Environment Images
    needs: build-basic
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-image: [ cfsbuildenv-doxygen, cfsbuildenv-linux, cfsbuildenv-mcdc, cfsbuildenv-rtems5, cfsbuildenv-rtems6, cfsbuildenv-arm-linux, cfsbuildenv-ubuntu22, cfsbuildenv-el9, cfsbuildenv-el8, cfsbuildenv-gaisler-sparc-rcc, cfsbuildenv-yocto ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build and push image
        uses: ./.github/actions/build-image
        with:
          target-image: ${{ matrix.target-image }}
          registry-token: ${{ secrets.GITHUB_TOKEN }}
