#! /bin/sh

### BEGIN INIT INFO
# Provides:        cfs
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start Core Flight System
### END INIT INFO

PATH=/sbin:/bin:/usr/bin:/usr/sbin

DAEMON=$(echo /cfs/core-*)
PIDFILE=/var/run/cfs.pid

# Source function library.
. /etc/init.d/functions

# Functions to do individual actions
startcfs(){
        # The -g option allows ntpd to step the time to correct it just
        # once.  The daemon will exit if the clock drifts too much after
        # this.  If ntpd seems to disappear after a while assume TICKADJ
        # above is set to a totally incorrect value.
        echo -n "Starting cfs: "
        start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- "$@"
        echo "done"
}
stopcfs(){
        echo -n "Stopping cfs: "
        start-stop-daemon --stop --quiet --oknodo -p $PIDFILE
        echo "done"
}

case "$1" in
  start)
        settick
        startdaemon
        ;;
  stop)
        stopdaemon
        ;;
  force-reload)
        stopdaemon
        startdaemon
        ;;
  restart)
        stopdaemon
        startdaemon
        ;;
  reload)
        stopdaemon
        startdaemon
        ;;
  status)
        ;;
  *)
        echo "Usage: cfs { start | stop | status | restart | reload }" >&2
        exit 1
        ;;
esac

exit 0
